version: "3"
services:
  database:
    image: postgres:13
    environment: 
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports: 
      - "${PUBLIC_DB_PORT}:5432"
    env_file: .env
  application:
    build: .
    ports:
      - "${PUBLIC_APP_PORT}:5000"
    env_file: .env
    volumes:
      - ./:/usr/app
  server:
    image: nginx:1.19
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${PUBLIC_SERVER_PORT}:80"
    env_file: .env


